---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flamingo-apps
  namespace: flux-system
  annotations:
    metadata.weave.works/flamingo-flamingo-apps: "https://localhost:8080/applications/argocd/flamingo-apps?view=tree"
spec:
  prune: true
  interval: 2m
  path: "./argo/apps"
  sourceRef:
    kind: OCIRepository
    name: flamingo
    namespace: flux-system
  timeout: 3m
  dependsOn:
    - name: flamingo-core