---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flamingo
  namespace: flux-system
spec:
  interval: 30s
  url: oci://ghcr.io/kameshsampath/manifests/flamingo
  ref:
    tag: v2.6