apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: hello-world
spec:
  interval: 30s
  url: oci://ghcr.io/kameshsampath/manifests/go-hello-world
  ref:
    tag: latest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/kameshsampath/manifests/go-hello-world
    targetRevision: latest
    path: ./serverless
  destination:
    server: https://kubernetes.default.svc