apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fsa-demo
  annotations:
    metadata.weave.works/flamingo-fsa-demo: "https://localhost:8080/applications/argocd/fsa-demo?view=tree"
spec:
  prune: true
  interval: 2m
  path: "./demo"
  sourceRef:
    kind: OCIRepository
    name: fsa-demo
  timeout: 3m
  patches:
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: argocd-server
        spec:
          ports:
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8080
            nodePort: 30080
      target:
        kind: Service
        labelSelector: "app.kubernetes.io/name=argocd-server"
