---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/flux-subsystem-argo/flamingo//demo/artifacts/fsa-installation

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
      spec:
        type: LoadBalancer
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
          nodePort: 30080
        - name: https
          port: 443
          protocol: TCP
          targetPort: 8080
          nodePort: 30443
    target:
      kind: Service
      labelSelector: "app.kubernetes.io/name=argocd-server"
