resources:
  - https://github.com/knative/serving/releases/download/knative-v1.9.0/serving-core.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.9.0/serving-default-domain.yaml
patchesStrategicMerge:
#########################################################################
# Remove all CRDS from core as they are installed using ../crds
#########################################################################
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: images.caching.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: certificates.networking.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: configurations.serving.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: clusterdomainclaims.networking.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: domainmappings.serving.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: ingresses.networking.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: metrics.autoscaling.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: podautoscalers.autoscaling.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: revisions.serving.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: routes.serving.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: serverlessservices.networking.internal.knative.dev
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: services.serving.knative.dev
    $patch: delete